/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import PUBLIC.*;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John
 */
public class FrmPaymentFee extends javax.swing.JPanel {

    /**
     * Creates new form DangKiMonHoc2
     */
    private ClsPaymentFee_Public pfPublic = new ClsPaymentFee_Public();
    private final ClsPaymentFee_BLL pfBLL = new ClsPaymentFee_BLL();
    private int percentReduce = 0;
    private String idSemesterYear = "";
    private String idRegisterForm = "";
    private int sumMoneyPaid = 0;
    private int sumMoneyDebt = 0;
    private int sumMoneyReduced = 0;
    private int moneyStudentPay;

    public FrmPaymentFee() {
        initComponents();
        txtIdStudent.setDocument(new ClsLimitDocument_BLL(20));
        txtMoneyStudentPay.setDocument(new ClsDigitsDocument_BLL(15));
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new org.jdesktop.swingx.JXPanel();
        TopInFull = new org.jdesktop.swingx.JXPanel();
        TopLeft1 = new org.jdesktop.swingx.JXPanel();
        lbMSSV1 = new org.jdesktop.swingx.JXLabel();
        HoTen1 = new org.jdesktop.swingx.JXLabel();
        cboSemester = new javax.swing.JComboBox();
        txtDeadlineToPayFee = new org.jdesktop.swingx.JXTextField();
        HoTen12 = new org.jdesktop.swingx.JXLabel();
        txtDeadlineReduceFee = new org.jdesktop.swingx.JXTextField();
        HoTen13 = new org.jdesktop.swingx.JXLabel();
        cboFirstYear = new javax.swing.JComboBox();
        TopLeft = new org.jdesktop.swingx.JXPanel();
        txtIdStudent = new org.jdesktop.swingx.JXTextField();
        lbMSSV = new org.jdesktop.swingx.JXLabel();
        txtNameOfStudent = new org.jdesktop.swingx.JXTextField();
        lbHoTen1 = new org.jdesktop.swingx.JXLabel();
        lbHoTen2 = new org.jdesktop.swingx.JXLabel();
        HoTen = new org.jdesktop.swingx.JXLabel();
        txtMayjor = new org.jdesktop.swingx.JXTextField();
        txtFacuty = new org.jdesktop.swingx.JXTextField();
        btnSearch_New = new org.jdesktop.swingx.JXButton();
        ControlPanel1 = new org.jdesktop.swingx.JXPanel();
        HoTen2 = new org.jdesktop.swingx.JXLabel();
        txtSumMoneyMustPay = new org.jdesktop.swingx.JXTextField();
        HoTen3 = new org.jdesktop.swingx.JXLabel();
        txtSumMoneyRegister = new org.jdesktop.swingx.JXTextField();
        HoTen4 = new org.jdesktop.swingx.JXLabel();
        txtSumMoneyPaid = new org.jdesktop.swingx.JXTextField();
        txtMoneyStudentPay = new org.jdesktop.swingx.JXTextField();
        HoTen5 = new org.jdesktop.swingx.JXLabel();
        txtSumMoneyDebt = new org.jdesktop.swingx.JXTextField();
        HoTen7 = new org.jdesktop.swingx.JXLabel();
        HoTen8 = new org.jdesktop.swingx.JXLabel();
        HoTen9 = new org.jdesktop.swingx.JXLabel();
        HoTen10 = new org.jdesktop.swingx.JXLabel();
        HoTen11 = new org.jdesktop.swingx.JXLabel();
        btnGetMoney = new org.jdesktop.swingx.JXButton();
        HoTen15 = new org.jdesktop.swingx.JXLabel();
        txtSumMoneyReduced = new org.jdesktop.swingx.JXTextField();
        HoTen16 = new org.jdesktop.swingx.JXLabel();
        HoTen6 = new org.jdesktop.swingx.JXLabel();
        TopPanel = new org.jdesktop.swingx.JXPanel();
        Title = new org.jdesktop.swingx.JXLabel();

        TopLeft1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời gian thu học phí"));

        lbMSSV1.setText("Học kì:");
        lbMSSV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen1.setText("Năm học");
        HoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3" }));
        cboSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSemesterActionPerformed(evt);
            }
        });

        txtDeadlineToPayFee.setEditable(false);

        HoTen12.setText("Hạn đóng học phí");
        HoTen12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDeadlineReduceFee.setEditable(false);

        HoTen13.setText("Hạn được giảm học phí");
        HoTen13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboFirstYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFirstYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopLeft1Layout = new javax.swing.GroupLayout(TopLeft1);
        TopLeft1.setLayout(TopLeft1Layout);
        TopLeft1Layout.setHorizontalGroup(
            TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeft1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLeft1Layout.createSequentialGroup()
                        .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboFirstYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TopLeft1Layout.createSequentialGroup()
                        .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoTen13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeadlineToPayFee, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtDeadlineReduceFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TopLeft1Layout.setVerticalGroup(
            TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeft1Layout.createSequentialGroup()
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFirstYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeadlineToPayFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeadlineReduceFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        TopLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sinh viên"));

        txtIdStudent.setEditable(false);
        txtIdStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdStudentKeyPressed(evt);
            }
        });

        lbMSSV.setText("Mssv:");
        lbMSSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNameOfStudent.setEditable(false);

        lbHoTen1.setText("Ngành:");
        lbHoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen2.setText("Khoa:");
        lbHoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen.setText("Họ tên:");
        HoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMayjor.setEditable(false);

        txtFacuty.setEditable(false);

        btnSearch_New.setText("Tìm kiếm");
        btnSearch_New.setEnabled(false);
        btnSearch_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopLeftLayout = new javax.swing.GroupLayout(TopLeft);
        TopLeft.setLayout(TopLeftLayout);
        TopLeftLayout.setHorizontalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TopLeftLayout.createSequentialGroup()
                        .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(TopLeftLayout.createSequentialGroup()
                                .addComponent(txtIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch_New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNameOfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TopLeftLayout.createSequentialGroup()
                        .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMayjor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFacuty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLeftLayout.setVerticalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameOfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMayjor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacuty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ControlPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin học phí"));

        HoTen2.setText("Tổng tiền phải đóng:");
        HoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSumMoneyMustPay.setEditable(false);

        HoTen3.setText("Tổng tiền đăng kí:");
        HoTen3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSumMoneyRegister.setEditable(false);

        HoTen4.setText("Tổng tiền đã đóng:");
        HoTen4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSumMoneyPaid.setEditable(false);

        txtMoneyStudentPay.setEditable(false);
        txtMoneyStudentPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoneyStudentPayKeyPressed(evt);
            }
        });

        HoTen5.setText("Số tiền thu:");
        HoTen5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSumMoneyDebt.setEditable(false);

        HoTen7.setText("VNĐ");
        HoTen7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen8.setText("VNĐ");
        HoTen8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen9.setText("VNĐ");
        HoTen9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen10.setText("VNĐ");
        HoTen10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen11.setText("VNĐ");
        HoTen11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGetMoney.setText("Thu Tiền");
        btnGetMoney.setEnabled(false);
        btnGetMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMoneyActionPerformed(evt);
            }
        });

        HoTen15.setText("Tổng tiền được giảm:");
        HoTen15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSumMoneyReduced.setEditable(false);

        HoTen16.setText("VNĐ");
        HoTen16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen6.setText("Tổng tiền còn nợ:");
        HoTen6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout ControlPanel1Layout = new javax.swing.GroupLayout(ControlPanel1);
        ControlPanel1.setLayout(ControlPanel1Layout);
        ControlPanel1Layout.setHorizontalGroup(
            ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ControlPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlPanel1Layout.createSequentialGroup()
                        .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ControlPanel1Layout.createSequentialGroup()
                                .addComponent(txtSumMoneyDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlPanel1Layout.createSequentialGroup()
                                .addComponent(txtSumMoneyPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlPanel1Layout.createSequentialGroup()
                                .addComponent(txtSumMoneyRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlPanel1Layout.createSequentialGroup()
                                .addComponent(txtSumMoneyMustPay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ControlPanel1Layout.createSequentialGroup()
                                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGetMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(txtMoneyStudentPay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ControlPanel1Layout.createSequentialGroup()
                        .addComponent(HoTen15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtSumMoneyReduced, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HoTen16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        ControlPanel1Layout.setVerticalGroup(
            ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumMoneyRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumMoneyMustPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumMoneyPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumMoneyReduced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSumMoneyDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoneyStudentPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopInFullLayout = new javax.swing.GroupLayout(TopInFull);
        TopInFull.setLayout(TopInFullLayout);
        TopInFullLayout.setHorizontalGroup(
            TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopInFullLayout.createSequentialGroup()
                .addComponent(TopLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ControlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TopInFullLayout.setVerticalGroup(
            TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopInFullLayout.createSequentialGroup()
                .addGroup(TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TopLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TopLeft1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ControlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TopLeft.getAccessibleContext().setAccessibleName("ThongTinNganh");

        javax.swing.GroupLayout FullPanelLayout = new javax.swing.GroupLayout(FullPanel);
        FullPanel.setLayout(FullPanelLayout);
        FullPanelLayout.setHorizontalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FullPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(TopInFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        FullPanelLayout.setVerticalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(TopInFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("THU HỌC PHÍ");
        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoadData() {
        //lay tat ca nam hoc da co        
        try {
            ResultSet rs = pfBLL.LoadFirstYear();
            cboFirstYear.addItem(" ");
            while (rs.next()) {
                int first = rs.getInt(1);
                int second = first + 1;
                cboFirstYear.addItem(String.valueOf(first) + " - " + String.valueOf(second));
            }
            cboFirstYear.setSelectedIndex(0);
        } catch (Exception ex) {
            Logger.getLogger(FrmPaymentFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnGetMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMoneyActionPerformed
        try {
            GetMoneyActionPerform();
        } catch (Exception ex) {
            Logger.getLogger(FrmPaymentFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGetMoneyActionPerformed

    private void GetMoneyActionPerform() throws Exception {
        //kiem tra input
        if (txtMoneyStudentPay.getText().isEmpty()) {
            return;
        }
        moneyStudentPay = Integer.parseInt(txtMoneyStudentPay.getText());
        if (moneyStudentPay > sumMoneyDebt) {
            JOptionPane.showMessageDialog(this, "Số tiền thu không được lớn hơn số tiền đang nợ!");
            return;
        }
        if (moneyStudentPay % 1000 > 0 || moneyStudentPay < 1000) {
            JOptionPane.showMessageDialog(this, "Số tiền thu nhỏ nhất là 1000 VNĐ\nVà có phần lẻ nhỏ nhất là 1000 VNĐ");
            return;
        }
        //tinh tien
        //kiểm tra xem số tiền sv đóng có bằng số tiền sv đang nợ hay không?
        //nếu không thì không giảm học phí cho lần đóng học phí này 
        if (moneyStudentPay != sumMoneyDebt && sumMoneyReduced > 0) {
            //reset lai tiền nợ lúc đầu, không giảm học phí theo quy định
            sumMoneyDebt += sumMoneyReduced;
            sumMoneyReduced = 0;//không giảm học phí
            txtSumMoneyReduced.setText("0");
            //hiển thì thông báo
            JOptionPane.showMessageDialog(this, "Sinh viên chưa hoàn thành học phí nên không được "
                    + "\ngiảm học phí theo quy định trong lần thu học phí này");
        }
        sumMoneyDebt -= moneyStudentPay;//giam bot no di
        txtSumMoneyDebt.setText(sumMoneyDebt + "");//+ "" để chuyen qua String

        moneyStudentPay += sumMoneyReduced;//neu duoc giam, thi cong so tien giam do vao so tien sinh vien dong
        sumMoneyPaid += moneyStudentPay;//cap nhat so tien da dong
        txtSumMoneyPaid.setText(sumMoneyPaid + "");

        //cap nhat gia tri trong bang phieu dang ky, va them phieu thu
        pfPublic.setMaNhanVien((new ClsStaffLoginInfo_Public()).getMaNV());
        pfPublic.setMaPhieuDK(idRegisterForm);
        pfPublic.setMaPhieuThu("PT0000");
        pfPublic.setNgayThu(new Date(Calendar.getInstance().getTime().getTime()));
        pfPublic.setSoTienDuocGiam(sumMoneyReduced);
        pfPublic.setSoTienThu(moneyStudentPay);
        pfPublic.setTienConNo(sumMoneyDebt);

        if (pfBLL.ExcutePaymentFee(sumMoneyPaid, pfPublic) > 0) {//neu luu du lieu thanh cong
            JOptionPane.showMessageDialog(this, "Thu học phí thành công!");
            txtMoneyStudentPay.setEditable(false);
            btnGetMoney.setEnabled(false);
            //reset lai bien luu tien, de cho lan thu hoc phi sau
            //percentReduce = 0;
            sumMoneyPaid = 0;
            sumMoneyDebt = 0;
            sumMoneyReduced = 0;
            moneyStudentPay = 0;
        } else {
            JOptionPane.showMessageDialog(this, "Thu học phí thất bại!");
        }

    }

    private void btnSearch_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_NewActionPerformed
        //thay doi chu hien thi tren button
        String label1 = "Sinh viên mới";
        String label2 = "Tìm kiếm";
        //neu là nút tìm kiếm
        if (btnSearch_New.getText().equals(label2)) {
            if (!CheckStudentAndLoadMoney()) {
                return;
            }
            txtIdStudent.setEditable(false);
            btnSearch_New.setText(label1);
        } else {//neu la nut Sinh vien moi
            NewStudent();
            //bat cac cbo hoc ki va nam hoc
            cboSemester.setEnabled(true);
            cboFirstYear.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearch_NewActionPerformed

    private void NewStudent() {
        txtIdStudent.setEditable(true);
        txtIdStudent.setText("");
        txtFacuty.setText("");
        txtMayjor.setText("");
        txtNameOfStudent.setText("");
        txtMoneyStudentPay.setText("");
        txtSumMoneyDebt.setText("");
        txtSumMoneyReduced.setText("");
        txtSumMoneyMustPay.setText("");
        txtSumMoneyPaid.setText("");
        txtSumMoneyRegister.setText("");
        btnGetMoney.setEnabled(false);
        txtMoneyStudentPay.setEditable(false);
        //chuyen text cua button
        btnSearch_New.setText("Tìm kiếm");
    }

    private void cboFirstYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFirstYearActionPerformed
        LoadSemesterInfo();
    }//GEN-LAST:event_cboFirstYearActionPerformed

    private void cboSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSemesterActionPerformed
        LoadSemesterInfo();
    }//GEN-LAST:event_cboSemesterActionPerformed

    private void txtIdStudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdStudentKeyPressed
        if (!txtIdStudent.getText().equals("")) {
            btnSearch_New.setEnabled(true);
        } else {
            btnSearch_New.setEnabled(false);
        }
        //neu bam phim enter thi kiem tra mssv
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (CheckStudentAndLoadMoney()) {
                txtIdStudent.setEditable(false);
                btnSearch_New.setText("Sinh viên mới");
            }
        }

    }//GEN-LAST:event_txtIdStudentKeyPressed

    private void txtMoneyStudentPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoneyStudentPayKeyPressed
        if (txtMoneyStudentPay.getText().isEmpty()) {
            btnGetMoney.setEnabled(false);
        } else {
            btnGetMoney.setEnabled(true);
        }
        //neu bam phim enter thi
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                GetMoneyActionPerform();
            } catch (Exception ex) {
                Logger.getLogger(FrmPaymentFee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtMoneyStudentPayKeyPressed

    private void LoadSemesterInfo() {
        if (cboFirstYear.getSelectedIndex() == 0 || cboSemester.getSelectedIndex() == 0) {
            return;
        }
        //lay han dong hoc phi, han duoc giam
        ClsSemesterYearPublic syPublic = new ClsSemesterYearPublic();
        syPublic.setFirstYear(Integer.parseInt(String.valueOf(cboFirstYear.getSelectedItem()).trim().split("\\ - ")[0]));
        syPublic.setSemester(Integer.parseInt(String.valueOf(cboSemester.getSelectedItem())));
        try {
            ResultSet rs = pfBLL.LoadAllDeadline(syPublic);
            if (rs.next()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Calendar calNow = Calendar.getInstance();
                calNow.setTime(calNow.getTime());
                //Date deadlineToRegister = ;
                Calendar deadlineToRegister = Calendar.getInstance();
                deadlineToRegister.setTime(rs.getDate(5));
                deadlineToRegister.roll(Calendar.DATE, true);//tăng thêm 1 ngày

                //Calendar.getInstance().before(deadlineToRegister);
                if (deadlineToRegister.after(calNow)) {
                    JOptionPane.showMessageDialog(this, "Chưa hết hạn đăng kí môn học\nKhông được thu học phí");
                    ClearText();
                    return;
                }

                Date deadlineToPayFee = rs.getDate(1);
                if (deadlineToPayFee.before(Calendar.getInstance().getTime())) {
                    JOptionPane.showMessageDialog(this, "Đã hết hạn đóng học phí");
                    ClearText();
                    return;
                }
                txtDeadlineToPayFee.setText(sdf.format(deadlineToPayFee));

                Date deadlineReduce = rs.getDate(2);
                if (deadlineReduce.after(Calendar.getInstance().getTime())) {
                    percentReduce = rs.getInt(3);
                }
                txtDeadlineReduceFee.setText(sdf.format(deadlineReduce));
                txtIdStudent.setEditable(true);
                idSemesterYear = rs.getString(4);//gan ma hoc ki nam hoc
            } else {
                JOptionPane.showMessageDialog(this, "Học kì không tồn tại");
                ClearText();
            }

        } catch (Exception ex) {
            Logger.getLogger(FrmPaymentFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ClearText() {
        txtDeadlineReduceFee.setText("");
        txtDeadlineToPayFee.setText("");
        txtIdStudent.setEditable(false);
        btnSearch_New.setEnabled(false);
        txtIdStudent.setText("");
        txtFacuty.setText("");
        txtMayjor.setText("");
        txtNameOfStudent.setText("");
        txtMoneyStudentPay.setText("");
        txtSumMoneyDebt.setText("");
        txtSumMoneyReduced.setText("");
        txtSumMoneyMustPay.setText("");
        txtSumMoneyPaid.setText("");
        txtSumMoneyRegister.setText("");
        btnGetMoney.setEnabled(false);
        txtMoneyStudentPay.setEditable(false);
        //chuyen text cua button
        btnSearch_New.setText("Tìm kiếm");
    }

    private boolean CheckStudentAndLoadMoney() {
        if (txtIdStudent.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã số sinh viên");
            NewStudent();
            return false;
        } else {
            //tat cac cbo hoc ki va nam hoc
            cboSemester.setEnabled(false);
            cboFirstYear.setEnabled(false);
            clsStudent_Public stPublic = new clsStudent_Public();
            stPublic.setIdStudent(txtIdStudent.getText());
            ClsRegisterCourses_BLL rcBLL = new ClsRegisterCourses_BLL();
            try {
                ResultSet rs = rcBLL.LoadStudentInfo(stPublic);
                if (rs.next()) {
                    //hien thi thong tin sinh vien
                    txtNameOfStudent.setText(rs.getString(1));
                    txtMayjor.setText(rs.getString(2));
                    txtFacuty.setText(rs.getString(3));
                    //load thong tin hoc phi
                    ClsRegisterForm_Public rfPublic = new ClsRegisterForm_Public();
                    rfPublic.setIdStudent(txtIdStudent.getText());
                    rfPublic.setIdSemesterYears(idSemesterYear);
                    rs = pfBLL.LoadFeeInfo(rfPublic);
                    if (rs.next()) {
                        txtSumMoneyRegister.setText(rs.getString(1).split("\\.")[0]);

                        int sumMoneyMustPay = rs.getInt(2);
                        txtSumMoneyMustPay.setText(sumMoneyMustPay + "");

                        sumMoneyPaid = rs.getInt(3);
                        txtSumMoneyPaid.setText(sumMoneyPaid + "");
                        //tong so tien duoc giam neu dong đủ hoc phi, trước hạn được giảm
                        //neu so tien da dong > 0, tuc la da dong hoc phi 1 lan roi, thi lan nay khong giam hoc phi nua
                        // if (txtSumMoneyPaid.getText().equals("0")) {//tong tien duoc giam, là căn cứ vào tổng số tiền sv phải đóng
                        float tempMoney = sumMoneyMustPay * ((float) percentReduce / 100);
                        int tempMoneyInt = 0;//bien de luu tien sau khi lam tron
                        //nếu phần lẻ sau dâu phẩy lớn hơn 1 thì cộng 1 vào phần trước dâu phẩy
                        String[] st = String.valueOf(tempMoney).split("\\.");
                        tempMoneyInt = Integer.parseInt(st[0]);//gan bang so o truoc dau phay
                        if (Integer.parseInt(st[1]) > 0) {
                            tempMoneyInt += 1;//da lam trong phan sau dau phay                                
                        }
                        //neu so tien le nho hơn 1000 dong, thì làm tron thanh 1000 dong
                        if (tempMoneyInt % 1000 >= 500) {//>=500d thi lam tron thanh 1000d
                            tempMoneyInt = (tempMoneyInt / 1000) * 1000 + 1000;//da lam tron, so tien nho nhat la 1000 đồng
                        } else {//<500d thi bo phan le di
                            tempMoneyInt = (tempMoneyInt / 1000) * 1000;
                        }
                        sumMoneyReduced = tempMoneyInt;
                        // }
                        txtSumMoneyReduced.setText(sumMoneyReduced + "");
                        if (sumMoneyMustPay == sumMoneyPaid) {//neu da het no thi k giam hoc phi nua
                            sumMoneyDebt = 0;
                        } else {//luôn giảm học phí nếu chưa hết nợ// nếu tiền được giảm khác 0
                            sumMoneyDebt = (sumMoneyMustPay - sumMoneyPaid) - sumMoneyReduced;
                        }
                        txtSumMoneyDebt.setText(sumMoneyDebt + "");
                        
                        idRegisterForm = rs.getString(4);//lay ma phieu dang ki
                        txtMoneyStudentPay.setEditable(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Sinh viên chưa đăng kí môn học");
                        //NewStudent();
                        return false;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mã số sinh viên không hợp lệ!");
                    NewStudent();
                    return false;
                }
            } catch (Exception ex) {
                Logger.getLogger(FrmPaymentFee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel ControlPanel1;
    private org.jdesktop.swingx.JXPanel FullPanel;
    private org.jdesktop.swingx.JXLabel HoTen;
    private org.jdesktop.swingx.JXLabel HoTen1;
    private org.jdesktop.swingx.JXLabel HoTen10;
    private org.jdesktop.swingx.JXLabel HoTen11;
    private org.jdesktop.swingx.JXLabel HoTen12;
    private org.jdesktop.swingx.JXLabel HoTen13;
    private org.jdesktop.swingx.JXLabel HoTen15;
    private org.jdesktop.swingx.JXLabel HoTen16;
    private org.jdesktop.swingx.JXLabel HoTen2;
    private org.jdesktop.swingx.JXLabel HoTen3;
    private org.jdesktop.swingx.JXLabel HoTen4;
    private org.jdesktop.swingx.JXLabel HoTen5;
    private org.jdesktop.swingx.JXLabel HoTen6;
    private org.jdesktop.swingx.JXLabel HoTen7;
    private org.jdesktop.swingx.JXLabel HoTen8;
    private org.jdesktop.swingx.JXLabel HoTen9;
    private org.jdesktop.swingx.JXLabel Title;
    private org.jdesktop.swingx.JXPanel TopInFull;
    private org.jdesktop.swingx.JXPanel TopLeft;
    private org.jdesktop.swingx.JXPanel TopLeft1;
    private org.jdesktop.swingx.JXPanel TopPanel;
    private org.jdesktop.swingx.JXButton btnGetMoney;
    private org.jdesktop.swingx.JXButton btnSearch_New;
    private javax.swing.JComboBox cboFirstYear;
    private javax.swing.JComboBox cboSemester;
    private org.jdesktop.swingx.JXLabel lbHoTen1;
    private org.jdesktop.swingx.JXLabel lbHoTen2;
    private org.jdesktop.swingx.JXLabel lbMSSV;
    private org.jdesktop.swingx.JXLabel lbMSSV1;
    private org.jdesktop.swingx.JXTextField txtDeadlineReduceFee;
    private org.jdesktop.swingx.JXTextField txtDeadlineToPayFee;
    private org.jdesktop.swingx.JXTextField txtFacuty;
    private org.jdesktop.swingx.JXTextField txtIdStudent;
    private org.jdesktop.swingx.JXTextField txtMayjor;
    private org.jdesktop.swingx.JXTextField txtMoneyStudentPay;
    private org.jdesktop.swingx.JXTextField txtNameOfStudent;
    private org.jdesktop.swingx.JXTextField txtSumMoneyDebt;
    private org.jdesktop.swingx.JXTextField txtSumMoneyMustPay;
    private org.jdesktop.swingx.JXTextField txtSumMoneyPaid;
    private org.jdesktop.swingx.JXTextField txtSumMoneyReduced;
    private org.jdesktop.swingx.JXTextField txtSumMoneyRegister;
    // End of variables declaration//GEN-END:variables

}
