/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import PUBLIC.*;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John
 */
public class FrmPositionAndAccess extends javax.swing.JPanel {

    /**
     * Creates new form DangKiMonHoc2
     */
    private final ClsPositionAndAccess_BLL paBLL = new ClsPositionAndAccess_BLL();
    private boolean themMoi = false;
    private DefaultTableModel dtm;
    private int rowSelected = 0;

    public FrmPositionAndAccess() {
        initComponents();
        txtNamePosition.setDocument(new ClsLimitDocument_BLL(50));
        dtm = (DefaultTableModel) tblListPosition.getModel();
        LayDuLieu();
        //
        tblListPosition.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListPosition.getColumnModel().getColumn(2).setMinWidth(0);
        tblListPosition.getColumnModel().getColumn(2).setMaxWidth(0);
        tblListPosition.getColumnModel().getColumn(2).setWidth(0);
        tblListPosition.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    rowSelected = tblListPosition.getSelectedRow();
                    if (rowSelected >= 0) {
                        btnXoa.setEnabled(true);
                    } else {
                        btnXoa.setEnabled(false);
                    }
                    if (dtm.getRowCount() > 0) {
                        btnXuatDS.setEnabled(true);
                    } else {
                        btnXuatDS.setEnabled(false);
                    }
                    if (!themMoi) {
                        bindingData(rowSelected);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(FrmPositionAndAccess.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new org.jdesktop.swingx.JXPanel();
        TopInFull = new org.jdesktop.swingx.JXPanel();
        TopLeft = new org.jdesktop.swingx.JXPanel();
        txtIdPosition = new org.jdesktop.swingx.JXTextField();
        lbMSSV = new org.jdesktop.swingx.JXLabel();
        txtNamePosition = new org.jdesktop.swingx.JXTextField();
        HoTen = new org.jdesktop.swingx.JXLabel();
        ControlPanel = new org.jdesktop.swingx.JXPanel();
        btnThem = new org.jdesktop.swingx.JXButton();
        btnCapNhat = new org.jdesktop.swingx.JXButton();
        btnHuyThaoTac = new org.jdesktop.swingx.JXButton();
        btnLuu = new org.jdesktop.swingx.JXButton();
        btnLamMoi = new org.jdesktop.swingx.JXButton();
        btnXoa = new org.jdesktop.swingx.JXButton();
        btnXuatDS = new org.jdesktop.swingx.JXButton();
        sfTimKiem = new org.jdesktop.swingx.JXSearchField();
        chkPhanBiet = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListPosition = new org.jdesktop.swingx.JXTable();
        TopLeft1 = new org.jdesktop.swingx.JXPanel();
        chkManageMinistry = new javax.swing.JCheckBox();
        chkCheckInScore = new javax.swing.JCheckBox();
        chkGetFee = new javax.swing.JCheckBox();
        chkRegisterCourse = new javax.swing.JCheckBox();
        chkManageStaff = new javax.swing.JCheckBox();
        chkChangeRegulation = new javax.swing.JCheckBox();
        chkManageStudent = new javax.swing.JCheckBox();
        chkSystemConfig = new javax.swing.JCheckBox();
        TopPanel = new org.jdesktop.swingx.JXPanel();
        Title = new org.jdesktop.swingx.JXLabel();

        TopLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chức vụ"));

        txtIdPosition.setEditable(false);

        lbMSSV.setText("Mã chức vụ:");
        lbMSSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNamePosition.setEditable(false);

        HoTen.setText("Tên chức vụ:");
        HoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout TopLeftLayout = new javax.swing.GroupLayout(TopLeft);
        TopLeft.setLayout(TopLeftLayout);
        TopLeftLayout.setHorizontalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNamePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLeftLayout.setVerticalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout TopInFullLayout = new javax.swing.GroupLayout(TopInFull);
        TopInFull.setLayout(TopInFullLayout);
        TopInFullLayout.setHorizontalGroup(
            TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopInFullLayout.setVerticalGroup(
            TopInFullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopInFullLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(TopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        TopLeft.getAccessibleContext().setAccessibleName("ThongTinNganh");

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Điều khiển"));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuyThaoTac.setText("Hủy Thao Tác");
        btnHuyThaoTac.setEnabled(false);
        btnHuyThaoTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyThaoTacActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setEnabled(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXuatDS.setText("Xuất Danh Sách");
        btnXuatDS.setEnabled(false);

        sfTimKiem.setToolTipText("Tìm kiếm");
        sfTimKiem.setPrompt("Tìm kiếm");
        sfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfTimKiemActionPerformed(evt);
            }
        });

        chkPhanBiet.setText("Phân biệt in hoa/in thường");
        chkPhanBiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPhanBietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnHuyThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkPhanBiet)
                .addGap(18, 18, 18)
                .addComponent(sfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkPhanBiet))))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách chức vụ"));

        tblListPosition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ", "Mã phân quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListPosition.setEditable(false);
        tblListPosition.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblListPosition);

        TopLeft1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin phân quyền"));

        chkManageMinistry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkManageMinistry.setText("Quản lý giáo vụ");
        chkManageMinistry.setEnabled(false);

        chkCheckInScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCheckInScore.setText("Nhập bảng điểm");
        chkCheckInScore.setEnabled(false);

        chkGetFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkGetFee.setText("Thu học phí");
        chkGetFee.setEnabled(false);

        chkRegisterCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkRegisterCourse.setText("Đăng kí môn học");
        chkRegisterCourse.setEnabled(false);

        chkManageStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkManageStaff.setText("Quản lý nhân viên");
        chkManageStaff.setEnabled(false);

        chkChangeRegulation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkChangeRegulation.setText("Thay đổi quy định");
        chkChangeRegulation.setEnabled(false);
        chkChangeRegulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChangeRegulationActionPerformed(evt);
            }
        });

        chkManageStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkManageStudent.setText("Quản lý sinh viên");
        chkManageStudent.setEnabled(false);

        chkSystemConfig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkSystemConfig.setText("Thiết lập hệ thống");
        chkSystemConfig.setEnabled(false);

        javax.swing.GroupLayout TopLeft1Layout = new javax.swing.GroupLayout(TopLeft1);
        TopLeft1.setLayout(TopLeft1Layout);
        TopLeft1Layout.setHorizontalGroup(
            TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeft1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkManageMinistry)
                    .addComponent(chkManageStudent))
                .addGap(18, 18, 18)
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLeft1Layout.createSequentialGroup()
                        .addComponent(chkGetFee)
                        .addGap(18, 18, 18)
                        .addComponent(chkCheckInScore)
                        .addGap(18, 18, 18)
                        .addComponent(chkRegisterCourse)
                        .addGap(18, 18, 18)
                        .addComponent(chkManageStaff)
                        .addGap(18, 18, 18)
                        .addComponent(chkChangeRegulation))
                    .addComponent(chkSystemConfig))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        TopLeft1Layout.setVerticalGroup(
            TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeft1Layout.createSequentialGroup()
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkManageMinistry)
                    .addComponent(chkCheckInScore)
                    .addComponent(chkGetFee)
                    .addComponent(chkRegisterCourse)
                    .addComponent(chkManageStaff)
                    .addComponent(chkChangeRegulation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkManageStudent)
                    .addComponent(chkSystemConfig))
                .addContainerGap())
        );

        javax.swing.GroupLayout FullPanelLayout = new javax.swing.GroupLayout(FullPanel);
        FullPanel.setLayout(FullPanelLayout);
        FullPanelLayout.setHorizontalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopInFull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        FullPanelLayout.setVerticalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(TopInFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("QUẢN LÝ CHỨC VỤ");
        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LayDuLieu() {
        try {
            //xoa cac dong trong bang hien tai neu co
            if(dtm.getRowCount()>0){
                for (int i = (dtm.getRowCount() - 1); i >=0; i--){
                    dtm.removeRow(i);
                }
            }
            ResultSet rs = paBLL.LoadPosition();
            while (rs.next()) {
                Vector data_rows = new Vector();
                data_rows.add(rs.getObject(1));
                data_rows.add(rs.getObject(2));
                data_rows.add(rs.getObject(3));
                dtm.addRow(data_rows);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmPositionAndAccess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bindingData(int row) throws ParseException {
        try {
            if (row < 0) {
                return;
            }
            chkManageMinistry.getModel().setSelected(false);
            chkCheckInScore.getModel().setSelected(false);
            chkGetFee.getModel().setSelected(false);
            chkRegisterCourse.getModel().setSelected(false);
            chkManageStaff.getModel().setSelected(false);
            chkChangeRegulation.getModel().setSelected(false);
            chkManageStudent.getModel().setSelected(false);
            chkSystemConfig.getModel().setSelected(false);
            
            txtIdPosition.setText(tblListPosition.getStringAt(row, 0));
            txtNamePosition.setText(tblListPosition.getStringAt(row, 1));
            String[] listAccess = tblListPosition.getStringAt(row, 2).split("\\,");
            for (int i = 0; i < listAccess.length; i++) {
                if (listAccess[i].equals("1")) {
                    chkManageMinistry.getModel().setSelected(true);
                }
                if (listAccess[i].equals("2")) {
                    chkGetFee.getModel().setSelected(true);
                }
                if (listAccess[i].equals("3")) {
                    chkCheckInScore.getModel().setSelected(true);
                }
                if (listAccess[i].equals("4")) {
                    chkRegisterCourse.getModel().setSelected(true);
                }
                if (listAccess[i].equals("5")) {
                    chkManageStaff.getModel().setSelected(true);
                }
                if (listAccess[i].equals("6")) {
                    chkChangeRegulation.getModel().setSelected(true);
                }
                if (listAccess[i].equals("7")) {
                    chkManageStudent.getModel().setSelected(true);
                }
                if (listAccess[i].equals("8")) {
                    chkSystemConfig.getModel().setSelected(true);
                }
            }
        } catch (Exception e) {
            Logger.getLogger(FrmStudentManager.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtIdPosition.setText("CV00");
        txtNamePosition.setText("");
        ChangeComponentStatus(true);
        ///
        chkManageMinistry.getModel().setSelected(false);
        chkCheckInScore.getModel().setSelected(false);
        chkGetFee.getModel().setSelected(false);
        chkRegisterCourse.getModel().setSelected(false);
        chkManageStaff.getModel().setSelected(false);
        chkChangeRegulation.getModel().setSelected(false);
        chkManageStudent.getModel().setSelected(false);
        chkSystemConfig.getModel().setSelected(false);
        //thay doi trang thai btn
        btnThem.setEnabled(false);
        btnCapNhat.setEnabled(false);
        btnLuu.setEnabled(true);
        btnLamMoi.setEnabled(true);
        btnXoa.setEnabled(false);
        btnXuatDS.setEnabled(false);
        btnHuyThaoTac.setEnabled(true);
        //gán cờ thêm mới để biết là đang thêm
        themMoi = true;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        ChangeComponentStatus(true);
        //thay doi trang thai btn
        btnThem.setEnabled(false);
        btnCapNhat.setEnabled(false);
        btnLuu.setEnabled(true);
        btnLamMoi.setEnabled(true);
        btnXoa.setEnabled(false);
        btnXuatDS.setEnabled(false);
        btnHuyThaoTac.setEnabled(true);
        //gán cờ thêm mới là false để biết là đang cập nhật
        themMoi = false;
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        //kiem tra input
        if (txtNamePosition.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên chức vụ");
            return;
        }
        if(!chkChangeRegulation.getModel().isSelected()
                &&!chkCheckInScore.getModel().isSelected()
                &&!chkGetFee.getModel().isSelected()
                &&!chkManageMinistry.getModel().isSelected()
                &&!chkManageStaff.getModel().isSelected()
                &&!chkManageStudent.getModel().isSelected()
                &&!chkRegisterCourse.getModel().isSelected()
                &&!chkSystemConfig.getModel().isSelected()){
            JOptionPane.showMessageDialog(this, "Chưa phân quyền cho chức vụ");
            return;
        }
        //chuan bi du lieu
        String listAcc = "";
        if(chkManageMinistry.getModel().isSelected()){
            listAcc = listAcc.concat("1");
        }
        if(chkGetFee.getModel().isSelected()){
            listAcc = listAcc.concat(",2");
        }
        if(chkCheckInScore.getModel().isSelected()){
            listAcc = listAcc.concat(",3");
        }
        if(chkRegisterCourse.getModel().isSelected()){
            listAcc = listAcc.concat(",4");
        }
        if(chkManageStaff.getModel().isSelected()){
            listAcc = listAcc.concat(",5");
        }
        if(chkChangeRegulation.getModel().isSelected()){
            listAcc = listAcc.concat(",6");
        }
        if(chkManageStudent.getModel().isSelected()){
            listAcc = listAcc.concat(",7");
        }
        if(chkSystemConfig.getModel().isSelected()){
            listAcc = listAcc.concat(",8");
        }
        ClsPositionAndAccess_Public paPublic = new ClsPositionAndAccess_Public();
        paPublic.setIdPosition(txtIdPosition.getText());
        paPublic.setNamePosition(txtNamePosition.getText());
        paPublic.setIdSetAccess(listAcc);
        try {
            if (themMoi)//nếu thêm mới thì gọi hàm thêm
            {
                ClsPositionAndAccess_BLL paBLL = new ClsPositionAndAccess_BLL();
                //goi den ham luu cua BLL
                if (paBLL.InsertPosition(paPublic) != 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    tblListPosition.setRowSelectionInterval(0, 0);
                    themMoi = false;
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    return;
                }
            } else //không thêm mới tức là cập nhật
            {
                if (paBLL.UpdatePosition(paPublic) != 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmPositionAndAccess.class.getName()).log(Level.SEVERE, null, ex);
        }

        //disable cac component
        ChangeComponentStatus(false);
        //thay doi trang thai btn
        btnThem.setEnabled(true);
        btnCapNhat.setEnabled(true);
        btnLuu.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnXoa.setEnabled(true);
        btnXuatDS.setEnabled(true);
        btnHuyThaoTac.setEnabled(false);
        //làm mới lại dữ liệu
        LayDuLieu();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void ChangeComponentStatus(boolean values){
        txtNamePosition.setEditable(values);
        chkManageMinistry.setEnabled(values);
        chkCheckInScore.setEnabled(values);
        chkGetFee.setEnabled(values);
        chkRegisterCourse.setEnabled(values);
        chkManageStaff.setEnabled(values);
        chkChangeRegulation.setEnabled(values);
        chkManageStudent.setEnabled(values);
        chkSystemConfig.setEnabled(values);
    }
    
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        if (txtNamePosition.isEditable()) {
            txtNamePosition.setText("");
            chkManageMinistry.getModel().setSelected(false);
            chkCheckInScore.getModel().setSelected(false);
            chkGetFee.getModel().setSelected(false);
            chkRegisterCourse.getModel().setSelected(false);
            chkManageStaff.getModel().setSelected(false);
            chkChangeRegulation.getModel().setSelected(false);
            chkManageStudent.getModel().setSelected(false);
            chkSystemConfig.getModel().setSelected(false);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtIdPosition.getText().isEmpty()) {
            return;
        }
        ClsPositionAndAccess_Public paPublic = new ClsPositionAndAccess_Public();
        paPublic.setIdPosition(txtIdPosition.getText());
        try {
            if (paBLL.DeletePosition(paPublic) != 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");                
                LayDuLieu();//làm mới dữ liệu
                tblListPosition.setRowSelectionInterval(0, 0);
            } else {
                JOptionPane.showMessageDialog(this, "Chức vụ hiện tại có liên quan đến dữ liệu nhân viên\nKhông thể xóa!");
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmPositionAndAccess.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Chức vụ hiện tại có liên quan đến dữ liệu nhân viên\nKhông thể xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void chkChangeRegulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChangeRegulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChangeRegulationActionPerformed

    private void btnHuyThaoTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyThaoTacActionPerformed
        btnHuyThaoTac.setEnabled(false);
        btnThem.setEnabled(true);
        btnCapNhat.setEnabled(true);
        btnLuu.setEnabled(false);
        btnLamMoi.setEnabled(false);
        ChangeComponentStatus(false);
        themMoi = false;
    }//GEN-LAST:event_btnHuyThaoTacActionPerformed

    private void chkPhanBietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPhanBietActionPerformed
        sfTimKiem.setText("");
    }//GEN-LAST:event_chkPhanBietActionPerformed

    private void sfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfTimKiemActionPerformed
        for (int i = 0; i < dtm.getRowCount(); i++) {
            for (int j = 0; j < dtm.getColumnCount(); j++) {
                if (chkPhanBiet.getModel().isSelected()) {//có phân biệt hoa thường
                    if (String.valueOf(dtm.getValueAt(i, j)).indexOf(sfTimKiem.getText()) >= 0) {
                        tblListPosition.setRowSelectionInterval(i, i);
                        tblListPosition.scrollRowToVisible(i);
                        return;
                    }
                } else {//khong phân biet
                    if (String.valueOf(dtm.getValueAt(i, j)).toUpperCase().indexOf(sfTimKiem.getText().toUpperCase()) >= 0) {
                        tblListPosition.setRowSelectionInterval(i, i);
                        tblListPosition.scrollRowToVisible(i);
                        return;
                    }
                }
            }
        }
    }//GEN-LAST:event_sfTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel ControlPanel;
    private org.jdesktop.swingx.JXPanel FullPanel;
    private org.jdesktop.swingx.JXLabel HoTen;
    private org.jdesktop.swingx.JXLabel Title;
    private org.jdesktop.swingx.JXPanel TopInFull;
    private org.jdesktop.swingx.JXPanel TopLeft;
    private org.jdesktop.swingx.JXPanel TopLeft1;
    private org.jdesktop.swingx.JXPanel TopPanel;
    private org.jdesktop.swingx.JXButton btnCapNhat;
    private org.jdesktop.swingx.JXButton btnHuyThaoTac;
    private org.jdesktop.swingx.JXButton btnLamMoi;
    private org.jdesktop.swingx.JXButton btnLuu;
    private org.jdesktop.swingx.JXButton btnThem;
    private org.jdesktop.swingx.JXButton btnXoa;
    private org.jdesktop.swingx.JXButton btnXuatDS;
    private javax.swing.JCheckBox chkChangeRegulation;
    private javax.swing.JCheckBox chkCheckInScore;
    private javax.swing.JCheckBox chkGetFee;
    private javax.swing.JCheckBox chkManageMinistry;
    private javax.swing.JCheckBox chkManageStaff;
    private javax.swing.JCheckBox chkManageStudent;
    private javax.swing.JCheckBox chkPhanBiet;
    private javax.swing.JCheckBox chkRegisterCourse;
    private javax.swing.JCheckBox chkSystemConfig;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel lbMSSV;
    private org.jdesktop.swingx.JXSearchField sfTimKiem;
    private org.jdesktop.swingx.JXTable tblListPosition;
    private org.jdesktop.swingx.JXTextField txtIdPosition;
    private org.jdesktop.swingx.JXTextField txtNamePosition;
    // End of variables declaration//GEN-END:variables
}
