/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import PUBLIC.ClsRegulationStatic_Public;
import PUBLIC.ClsRegulation_Public;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXTextField;

/**
 *
 * @author John
 */
public class FrmRegulation extends javax.swing.JPanel {

    /**
     * Creates new form QuyDinh
     */
    private final ClsRegulationBLL reBLL = new ClsRegulationBLL();
    private ResultSet rsRegulation;

    public FrmRegulation() {
        initComponents();
        LayDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new org.jdesktop.swingx.JXPanel();
        TopLeft = new org.jdesktop.swingx.JXPanel();
        lbHoTen2 = new org.jdesktop.swingx.JXLabel();
        lbHoTen3 = new org.jdesktop.swingx.JXLabel();
        HoTen1 = new org.jdesktop.swingx.JXLabel();
        lbHoTen4 = new org.jdesktop.swingx.JXLabel();
        lbMSSV1 = new org.jdesktop.swingx.JXLabel();
        lbHoTen5 = new org.jdesktop.swingx.JXLabel();
        HoTen2 = new org.jdesktop.swingx.JXLabel();
        spMaxCredit = new javax.swing.JSpinner();
        spMinScore = new javax.swing.JSpinner();
        spMaxScore = new javax.swing.JSpinner();
        spPassScore = new javax.swing.JSpinner();
        spMinStaff = new javax.swing.JSpinner();
        spMaxStaff = new javax.swing.JSpinner();
        spMinStudent = new javax.swing.JSpinner();
        ControlPanel = new org.jdesktop.swingx.JXPanel();
        btnCapNhat = new org.jdesktop.swingx.JXButton();
        btnLuu = new org.jdesktop.swingx.JXButton();
        btnLamMoi = new org.jdesktop.swingx.JXButton();
        btnHuyCapNhat = new org.jdesktop.swingx.JXButton();
        TopPanel = new org.jdesktop.swingx.JXPanel();
        Title = new org.jdesktop.swingx.JXLabel();

        TopLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách quy định"));

        lbHoTen2.setText("Số tín chỉ tối đa trên một học kì:");
        lbHoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen3.setText("Tuổi nhân viên tối thiểu:");
        lbHoTen3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen1.setText("Điểm đạt:");
        HoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen4.setText("Điểm tối đa:");
        lbHoTen4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbMSSV1.setText("Điểm tối thiểu:");
        lbMSSV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen5.setText("Tuổi sinh viên tối thiểu:");
        lbHoTen5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen2.setText("Tuổi nhân viên tối đa:");
        HoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        spMaxCredit.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        spMaxCredit.setEnabled(false);

        spMinScore.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
        spMinScore.setEnabled(false);

        spMaxScore.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
        spMaxScore.setEnabled(false);

        spPassScore.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
        spPassScore.setEnabled(false);

        spMinStaff.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spMinStaff.setEnabled(false);

        spMaxStaff.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spMaxStaff.setEnabled(false);

        spMinStudent.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spMinStudent.setEnabled(false);

        javax.swing.GroupLayout TopLeftLayout = new javax.swing.GroupLayout(TopLeft);
        TopLeft.setLayout(TopLeftLayout);
        TopLeftLayout.setHorizontalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spMaxCredit)
                    .addComponent(spMinScore, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMaxScore, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPassScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(spMinStaff, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMaxStaff, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMinStudent, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLeftLayout.setVerticalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMaxCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMaxScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPassScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMaxStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Điều khiển"));
        ControlPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        ControlPanel.add(btnCapNhat);

        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        ControlPanel.add(btnLuu);

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setEnabled(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        ControlPanel.add(btnLamMoi);

        btnHuyCapNhat.setText("Hủy cập nhật");
        btnHuyCapNhat.setEnabled(false);
        btnHuyCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyCapNhatActionPerformed(evt);
            }
        });
        ControlPanel.add(btnHuyCapNhat);

        javax.swing.GroupLayout FullPanelLayout = new javax.swing.GroupLayout(FullPanel);
        FullPanel.setLayout(FullPanelLayout);
        FullPanelLayout.setHorizontalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        FullPanelLayout.setVerticalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        TopLeft.getAccessibleContext().setAccessibleName("ThongTinNganh");

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("QUY ĐỊNH");
        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LayDuLieu() {
        try {
            rsRegulation = reBLL.LoadRegulation();
            if (rsRegulation.next()) {
                //binding cac gia tri vao textbox
                spMaxCredit.setValue(rsRegulation.getInt(2));
                rsRegulation.next();
                spMinScore.setValue(rsRegulation.getFloat(2));
                rsRegulation.next();
                spMaxScore.setValue(rsRegulation.getFloat(2));
                rsRegulation.next();
                spPassScore.setValue(rsRegulation.getFloat(2));
                rsRegulation.next();
                spMinStaff.setValue(rsRegulation.getInt(2));
                rsRegulation.next();
                spMaxStaff.setValue(rsRegulation.getInt(2));
                rsRegulation.next();
                spMinStudent.setValue(rsRegulation.getInt(2));
            } else {
                //neu khong co tham so nao thi tu dong them tham so rong
                reBLL.InsertRegulation();
                //them cac gia tri 0 vao textbox
                spMaxCredit.setValue(0);
                spMaxScore.setValue(0);
                spMaxStaff.setValue(0);
                spMinScore.setValue(0);
                spMinStudent.setValue(0);
                spMinStaff.setValue(0);
                spPassScore.setValue(0);
            }

        } catch (Exception ex) {
            Logger.getLogger(FrmRegulation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        spMaxCredit.setEnabled(true);
        spMaxScore.setEnabled(true);
        spMaxStaff.setEnabled(true);
        spMinScore.setEnabled(true);
        spMinStudent.setEnabled(true);
        spMinStaff.setEnabled(true);
        spPassScore.setEnabled(true);
        //thay doi trang thai btn

        btnCapNhat.setEnabled(false);
        btnLuu.setEnabled(true);
        btnLamMoi.setEnabled(true);
        btnHuyCapNhat.setEnabled(true);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        //kiem tra input
        if (spMaxCredit.getValue() == null
                || spMaxScore.getValue() == null
                || spMaxStaff.getValue() == null
                || spMinScore.getValue() == null
                || spMinStaff.getValue() == null
                || spMinStudent.getValue() == null
                || spPassScore.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin");
            return;
        }
        //kiem tra rang buoc tuoi, diem 
        if((float)spMinScore.getValue() > (float)spPassScore.getValue()){
            JOptionPane.showMessageDialog(this, "Điểm tối thiểu phải nhỏ hơn hoặc bằng điểm đạt");
            return;
        }
        if((float)spMaxScore.getValue() < (float)spPassScore.getValue()){
            JOptionPane.showMessageDialog(this, "Điểm tối đa phải lớn hơn hoặc bằng điểm đạt");
            return;
        }
        if((int)spMinStaff.getValue() > (int)spMaxStaff.getValue()){
            JOptionPane.showMessageDialog(this, "Tuổi nhân viên tối thiểu phải nhỏ hơn tuổi nhân viên tối đa");
            return;
        }
        //tao doi tuong public
        ClsRegulation_Public p = new ClsRegulation_Public();
        p.setPassScore((float) spPassScore.getValue());
        p.setMaxScore((float) spMaxScore.getValue());
        p.setMinScore((float) spMinScore.getValue());
        p.setMinStaffYearOld((int) spMinStaff.getValue());
        p.setMinStudentYearOld((int) spMinStudent.getValue());
        p.setMaxStaffYearOld((int) spMaxStaff.getValue());
        p.setMaxCredit((int) spMaxCredit.getValue());
        try {
            if (reBLL.UpdateRegulation(p) != 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                LoadNewStatic();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmRegulation.class.getName()).log(Level.SEVERE, null, ex);
        }

        //disable cac component
        spMaxCredit.setEnabled(false);
        spMaxScore.setEnabled(false);
        spMaxStaff.setEnabled(false);
        spMinScore.setEnabled(false);
        spMinStudent.setEnabled(false);
        spMinStaff.setEnabled(false);
        spPassScore.setEnabled(false);
        //thay doi trang thai btn
        btnCapNhat.setEnabled(true);
        btnLuu.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnHuyCapNhat.setEnabled(false);
        //làm mới lại dữ liệu
        LayDuLieu();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void LoadNewStatic() throws Exception {
        //load cac quy dinh len 1 class Static de kiem tra
        ClsRegulationBLL reBLL = new ClsRegulationBLL();
        ClsRegulationStatic_Public rsPulic = new ClsRegulationStatic_Public();
        ResultSet rs = reBLL.LoadRegulation();
        if (rs.next()) {
            rsPulic.setMaxCredit(rs.getInt(2));
            rs.next();
            rsPulic.setMinScore(rs.getFloat(2));
            rs.next();
            rsPulic.setMaxScore(rs.getFloat(2));
            rs.next();
            rsPulic.setPassScore(rs.getFloat(2));
            rs.next();
            rsPulic.setMinStaffYearOld(rs.getInt(2));
            rs.next();
            rsPulic.setMaxStaffYearOld(rs.getInt(2));
            rs.next();
            rsPulic.setMinStudentYearOld(rs.getInt(2));
        }
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        if (spMaxCredit.isEnabled()) {
            spMaxCredit.setValue(0);
            spMaxScore.setValue(0);
            spMaxStaff.setValue(0);
            spMinScore.setValue(0);
            spMinStudent.setValue(0);
            spMinStaff.setValue(0);
            spPassScore.setValue(0);
        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyCapNhatActionPerformed
        //disable cac component
        spMaxCredit.setEnabled(false);
        spMaxScore.setEnabled(false);
        spMaxStaff.setEnabled(false);
        spMinScore.setEnabled(false);
        spMinStudent.setEnabled(false);
        spMinStaff.setEnabled(false);
        spPassScore.setEnabled(false);
        //thay doi trang thai btn
        btnCapNhat.setEnabled(true);
        btnLuu.setEnabled(false);
        btnLamMoi.setEnabled(false);
        btnHuyCapNhat.setEnabled(false);
        //làm mới lại dữ liệu
        LayDuLieu();
    }//GEN-LAST:event_btnHuyCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel ControlPanel;
    private org.jdesktop.swingx.JXPanel FullPanel;
    private org.jdesktop.swingx.JXLabel HoTen1;
    private org.jdesktop.swingx.JXLabel HoTen2;
    private org.jdesktop.swingx.JXLabel Title;
    private org.jdesktop.swingx.JXPanel TopLeft;
    private org.jdesktop.swingx.JXPanel TopPanel;
    private org.jdesktop.swingx.JXButton btnCapNhat;
    private org.jdesktop.swingx.JXButton btnHuyCapNhat;
    private org.jdesktop.swingx.JXButton btnLamMoi;
    private org.jdesktop.swingx.JXButton btnLuu;
    private org.jdesktop.swingx.JXLabel lbHoTen2;
    private org.jdesktop.swingx.JXLabel lbHoTen3;
    private org.jdesktop.swingx.JXLabel lbHoTen4;
    private org.jdesktop.swingx.JXLabel lbHoTen5;
    private org.jdesktop.swingx.JXLabel lbMSSV1;
    private javax.swing.JSpinner spMaxCredit;
    private javax.swing.JSpinner spMaxScore;
    private javax.swing.JSpinner spMaxStaff;
    private javax.swing.JSpinner spMinScore;
    private javax.swing.JSpinner spMinStaff;
    private javax.swing.JSpinner spMinStudent;
    private javax.swing.JSpinner spPassScore;
    // End of variables declaration//GEN-END:variables
}
