/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import DAL.Crypter;
import PUBLIC.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXTextField;

/**
 *
 * @author John
 */
public class FrmStaffInfo extends javax.swing.JPanel {

    /**
     * Creates new form QuyDinh
     */
    private final ClsRegulationBLL reBLL = new ClsRegulationBLL();
    private ClsStaffLoginInfo_Public sfiPublic = new ClsStaffLoginInfo_Public();

    public FrmStaffInfo() {
        initComponents();
        pasConfirm.setDocument(new ClsLimitDocument_BLL(100));
        pasCurrent.setDocument(new ClsLimitDocument_BLL(100));
        pasNew.setDocument(new ClsLimitDocument_BLL(100));
        LayDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new org.jdesktop.swingx.JXPanel();
        TopLeft = new org.jdesktop.swingx.JXPanel();
        lbHoTen2 = new org.jdesktop.swingx.JXLabel();
        txtIdStaff = new org.jdesktop.swingx.JXTextField();
        txtAdress = new org.jdesktop.swingx.JXTextField();
        lbHoTen3 = new org.jdesktop.swingx.JXLabel();
        HoTen1 = new org.jdesktop.swingx.JXLabel();
        txtDateOfBirth = new org.jdesktop.swingx.JXTextField();
        txtSex = new org.jdesktop.swingx.JXTextField();
        lbHoTen4 = new org.jdesktop.swingx.JXLabel();
        lbMSSV1 = new org.jdesktop.swingx.JXLabel();
        txtNameStaff = new org.jdesktop.swingx.JXTextField();
        HoTen2 = new org.jdesktop.swingx.JXLabel();
        txtUserName = new org.jdesktop.swingx.JXTextField();
        ControlPanel = new org.jdesktop.swingx.JXPanel();
        btnChangPass = new org.jdesktop.swingx.JXButton();
        btnSave = new org.jdesktop.swingx.JXButton();
        btnCancel = new org.jdesktop.swingx.JXButton();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        lbHoTen5 = new org.jdesktop.swingx.JXLabel();
        lbHoTen6 = new org.jdesktop.swingx.JXLabel();
        lbHoTen7 = new org.jdesktop.swingx.JXLabel();
        pasCurrent = new javax.swing.JPasswordField();
        pasNew = new javax.swing.JPasswordField();
        pasConfirm = new javax.swing.JPasswordField();
        lbHoTen8 = new org.jdesktop.swingx.JXLabel();
        TopPanel = new org.jdesktop.swingx.JXPanel();
        Title = new org.jdesktop.swingx.JXLabel();

        TopLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        lbHoTen2.setText("Mã nhân viên:");
        lbHoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtIdStaff.setEditable(false);
        txtIdStaff.setMinimumSize(new java.awt.Dimension(6, 15));
        txtIdStaff.setPreferredSize(new java.awt.Dimension(6, 18));

        txtAdress.setEditable(false);
        txtAdress.setMinimumSize(new java.awt.Dimension(6, 15));
        txtAdress.setPreferredSize(new java.awt.Dimension(6, 18));

        lbHoTen3.setText("Địa chỉ:");
        lbHoTen3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        HoTen1.setText("Ngày sinh:");
        HoTen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDateOfBirth.setEditable(false);
        txtDateOfBirth.setMinimumSize(new java.awt.Dimension(6, 15));
        txtDateOfBirth.setPreferredSize(new java.awt.Dimension(6, 18));

        txtSex.setEditable(false);
        txtSex.setMinimumSize(new java.awt.Dimension(6, 15));
        txtSex.setPreferredSize(new java.awt.Dimension(6, 18));

        lbHoTen4.setText("Giới tính:");
        lbHoTen4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbMSSV1.setText("Họ tên:");
        lbMSSV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNameStaff.setEditable(false);
        txtNameStaff.setMinimumSize(new java.awt.Dimension(6, 15));
        txtNameStaff.setPreferredSize(new java.awt.Dimension(6, 18));

        HoTen2.setText("Tên đăng nhập:");
        HoTen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtUserName.setEditable(false);
        txtUserName.setMinimumSize(new java.awt.Dimension(6, 15));
        txtUserName.setPreferredSize(new java.awt.Dimension(6, 18));

        javax.swing.GroupLayout TopLeftLayout = new javax.swing.GroupLayout(TopLeft);
        TopLeft.setLayout(TopLeftLayout);
        TopLeftLayout.setHorizontalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNameStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        TopLeftLayout.setVerticalGroup(
            TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Điều khiển"));
        ControlPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnChangPass.setText("Đổi mật khẩu");
        btnChangPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangPassActionPerformed(evt);
            }
        });
        ControlPanel.add(btnChangPass);

        btnSave.setText("Lưu");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        ControlPanel.add(btnSave);

        btnCancel.setText("Hủy thao tác");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        ControlPanel.add(btnCancel);

        jXPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đổi mật khẩu"));

        lbHoTen5.setText("Mật khẩu hiện tại:");
        lbHoTen5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen6.setText("Mật khẩu mới:");
        lbHoTen6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbHoTen7.setText("Xác nhận mật khẩu:");
        lbHoTen7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pasCurrent.setEditable(false);

        pasNew.setEditable(false);

        pasConfirm.setEditable(false);

        lbHoTen8.setText("Độ dài tối thiểu là 8 kí tự");
        lbHoTen8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(lbHoTen6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(pasNew))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(lbHoTen7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pasConfirm))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(lbHoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHoTen8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHoTen8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout FullPanelLayout = new javax.swing.GroupLayout(FullPanel);
        FullPanel.setLayout(FullPanelLayout);
        FullPanelLayout.setHorizontalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        FullPanelLayout.setVerticalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(TopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        TopLeft.getAccessibleContext().setAccessibleName("ThongTinNganh");

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("THÔNG TIN NHÂN VIÊN");
        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LayDuLieu() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtIdStaff.setText(sfiPublic.getMaNV());
        txtNameStaff.setText(sfiPublic.getTenNV());
        txtDateOfBirth.setText(sdf.format(sfiPublic.getNgaySinh()));
        txtSex.setText(sfiPublic.getGioiTinh());
        txtAdress.setText(sfiPublic.getDiaChi());
        txtUserName.setText(sfiPublic.getMaNV());
    }


    private void btnChangPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangPassActionPerformed
        pasConfirm.setEditable(true);
        pasCurrent.setEditable(true);
        pasNew.setEditable(true);
        pasConfirm.setText("");
        pasCurrent.setText("");
        pasNew.setText("");

        btnChangPass.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_btnChangPassActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //kiem tra input
        if (new String(pasCurrent.getPassword()).isEmpty()
                || new String(pasNew.getPassword()).isEmpty()
                || new String(pasConfirm.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ mật khẩu");
            return;
        }
        if (new String(pasNew.getPassword()).length() < 8
                || new String(pasConfirm.getPassword()).length() < 8) {
            JOptionPane.showMessageDialog(this, "Độ dài mật khẩu tối thiểu là 8 kí tự");
            return;
        }
        //kiểm tra mật khẩu hiện tại xem có đúng không?
        clsStaff_Public nvP = new clsStaff_Public();
        nvP.setTenDN(txtUserName.getText());
        LoginBLL lgBLL = new LoginBLL();
        try {
            ResultSet rs = lgBLL.GetPassByUserName(nvP);
            if (rs.next()) {
                String matkhau = rs.getString(1);
                if (Crypter.encryptMD5(new String(pasCurrent.getPassword())).equals(matkhau)) {
                    //neu nhap mat khau cu dung, thi kiểm tra 2 cái mật khẩu mới xem có giống nhau hay không?
                    if (!Arrays.equals(pasNew.getPassword(), pasConfirm.getPassword())) {
                        JOptionPane.showMessageDialog(this, "Mật khẩu mới không trùng nhau\nVui lòng kiểm tra lại!");
                    } else {//neu mat khau mới giống nhau rồi thì cập nhật mật khẩu
                        //ma hoa mat khau
                        String newPass = Crypter.encryptMD5(new String(pasNew.getPassword()));
                        nvP.setTenDN(txtUserName.getText());
                        nvP.setMatKhau(newPass);
                        clsStaff_BLL sfBLL = new clsStaff_BLL();
                        if (sfBLL.UpdatePassWord(nvP) > 0) {
                            JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công!");
                            //thay doi trang thai btn, pass
                            pasConfirm.setEditable(false);
                            pasCurrent.setEditable(false);
                            pasNew.setEditable(false);
                            btnChangPass.setEnabled(true);
                            btnSave.setEnabled(false);
                            btnCancel.setEnabled(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thất bại!");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không thể cập nhật mật khẩu vào lúc này");
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmStaffInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        pasConfirm.setText("");
        pasCurrent.setText("");
        pasNew.setText("");
        pasConfirm.setEditable(false);
        pasCurrent.setEditable(false);
        pasNew.setEditable(false);        

        //thay doi trang thai btn
        btnChangPass.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel ControlPanel;
    private org.jdesktop.swingx.JXPanel FullPanel;
    private org.jdesktop.swingx.JXLabel HoTen1;
    private org.jdesktop.swingx.JXLabel HoTen2;
    private org.jdesktop.swingx.JXLabel Title;
    private org.jdesktop.swingx.JXPanel TopLeft;
    private org.jdesktop.swingx.JXPanel TopPanel;
    private org.jdesktop.swingx.JXButton btnCancel;
    private org.jdesktop.swingx.JXButton btnChangPass;
    private org.jdesktop.swingx.JXButton btnSave;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel lbHoTen2;
    private org.jdesktop.swingx.JXLabel lbHoTen3;
    private org.jdesktop.swingx.JXLabel lbHoTen4;
    private org.jdesktop.swingx.JXLabel lbHoTen5;
    private org.jdesktop.swingx.JXLabel lbHoTen6;
    private org.jdesktop.swingx.JXLabel lbHoTen7;
    private org.jdesktop.swingx.JXLabel lbHoTen8;
    private org.jdesktop.swingx.JXLabel lbMSSV1;
    private javax.swing.JPasswordField pasConfirm;
    private javax.swing.JPasswordField pasCurrent;
    private javax.swing.JPasswordField pasNew;
    private org.jdesktop.swingx.JXTextField txtAdress;
    private org.jdesktop.swingx.JXTextField txtDateOfBirth;
    private org.jdesktop.swingx.JXTextField txtIdStaff;
    private org.jdesktop.swingx.JXTextField txtNameStaff;
    private org.jdesktop.swingx.JXTextField txtSex;
    private org.jdesktop.swingx.JXTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
