/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Report;

import BLL.Item_Cbx;
import BLL.clsFacultyBLL;
import BLL.clsMayjors_BLL;
import BLL.clsRegisterForm_BLL;
import BLL.clsScholastic_BLL;
import BLL.clsStudent_BLL;
import DAL.SQLServerConnector;
import GUI.LineNumberTableRowHeader;
import GUI.frmMain;
import PUBLIC.PhieuDangKyPublic;
import PUBLIC.clsFaculty_Public;
import PUBLIC.clsMayjors_Public;
import PUBLIC.clsStudent_Public;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hung
 */
public class rpStateFee extends javax.swing.JPanel {

    /**
     * Creates new form rpStateFee
     */
    
    private ResultSet rs;
    private clsFacultyBLL FaBLL = new clsFacultyBLL();
    private clsMayjors_BLL MaBLL = new clsMayjors_BLL();
    private clsMayjors_Public mayjorsPublic = new clsMayjors_Public();
    private clsFaculty_Public faPublic = new clsFaculty_Public();
    private String idFaculty = "";
    private String idMayjors = "";
    private String yearOfApply = "";
    private Integer noSemeter;
    private Integer year1;
    private Integer year2;
    private clsStudent_BLL stBLL = new clsStudent_BLL();
    private clsStudent_Public stPublic = new clsStudent_Public();
    private ArrayList<clsFaculty_Public> listFaculty;
    private DefaultTableModel dtmListStudent;
    private DefaultTableModel dtmListStudentDetail;
    private Item_Cbx itemFaculty;
    private Item_Cbx itemMayjors;
    private Item_Cbx itemYearApply;
    private Item_Cbx itemNoSemeter;
    private Item_Cbx itemYear;
    private Item_Cbx itemStateRegister;
    final DefaultComboBoxModel dfModel = new DefaultComboBoxModel();
    DefaultComboBoxModel modelMayjors;
    DefaultComboBoxModel modelYearApply;
    DefaultComboBoxModel modelCondition;
    DefaultComboBoxModel modelScholatis;
    DefaultComboBoxModel modelSemeter;

    String selectedData = "";
    String getNameStudent = "";
    String getTotal = "";
    String getFaculty = "";
    String getMayjors = "";
    String getSemeter = "";
    String getScholatic="";
    private clsScholastic_BLL scholBLL;
    private clsRegisterForm_BLL regFormBLL;
    private PhieuDangKyPublic regFormPublic = new PhieuDangKyPublic();

    frmMain frm = new frmMain();
    SQLServerConnector conn;


    public rpStateFee() {
        try {
            initComponents();
            Load();
        } catch (Exception ex) {
            Logger.getLogger(rpStateFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Load() throws Exception {
        try {
            this.modelMayjors = new DefaultComboBoxModel(fAddtoArrr_fill_cbMayjors().toArray());
            this.modelYearApply = new DefaultComboBoxModel(fAddtoArr_fill_cbYearApply().toArray());
            this.modelCondition = new DefaultComboBoxModel(fAddtoArrr_fill_cbCondition().toArray());
            this.modelSemeter = new DefaultComboBoxModel(fAddtoArr_fill_cbSemeter().toArray());
            this.modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
            fFillCombobox_cbFaculty();
            fFillCombobox_cbMayjors();
            FillCombobox_cbYearApply();
            fFillCombobox_cbSemeter();
            fFillCombobox_cbScholatic();
            fFillCombobox_cbState();
            eventOnTable();
        } catch (Exception ex) {
            throw ex;
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    /**
     * @Hung Date: 06/05/2014 Tạo ra mảng để lưu các giá trị trong combobox để
     * setModel mặc định giá trị ban đầu cho combobox
     */
    private ArrayList<Item_Cbx> fAddtoArrr_fill_cbMayjors() {
        ArrayList<Item_Cbx> arr = new ArrayList<>();
        try {
            mayjorsPublic.setIdFaculty(idFaculty);
            rs = MaBLL.fLoadInfoMayjors_idFaculty(mayjorsPublic);
            arr.add(new Item_Cbx("01", "Tất cả"));
            while (rs.next()) {
                arr.add(new Item_Cbx(rs.getNString(1), rs.getNString(2)));
                cbMayjors.setModel(modelMayjors);
            }

        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
        return arr;
    }

    /**
     * @HungNgoc Date: 06/05/2014 tạo mảng cho combobox Năm nhập học
     */
    private ArrayList<Item_Cbx> fAddtoArr_fill_cbYearApply() {
        ArrayList<Item_Cbx> cbYearArr = new ArrayList<>();
        try {
            stBLL = new clsStudent_BLL();
            rs = stBLL.fLoad_Year_Of_StudentApply();
            cbYearArr.add(new Item_Cbx("Tất cả"));
            while (rs.next()) {
                cbYearArr.add(new Item_Cbx(rs.getString(1)));
            }
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cbYearArr;
    }

    /**
     * @HungNgoc Date: 10/06/2014
     *
     */
    private ArrayList<Item_Cbx> fAddtoArr_fill_cbScholastic() {
        scholBLL = new clsScholastic_BLL();
        ArrayList<Item_Cbx> cbScholastic = new ArrayList<>();
        try {
            rs = scholBLL.LOAD_SCHOLASTIC();
            cbScholastic.add(new Item_Cbx("1", "Tất cả"));
            while (rs.next()) {

                String yearFirst = "";
                String yearSecond = "";
                yearFirst = (String) rs.getString(1);
                yearSecond = (String) rs.getString(2);
                cbScholastic.add(new Item_Cbx(yearFirst + "-" + yearSecond));
            }
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cbScholastic;
    }

    /**
     * @HungNgoc
     *
     */
    private ArrayList<Item_Cbx> fAddtoArr_fill_cbSemeter() {
        scholBLL = new clsScholastic_BLL();
        ArrayList<Item_Cbx> cbSemeterArr = new ArrayList<>();
        try {
            rs = scholBLL.LOAD_SEMETER();
            cbSemeterArr.add(new Item_Cbx("1", "Tất cả"));
            while (rs.next()) {
                cbSemeterArr.add(new Item_Cbx(rs.getString(1)));
            }
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cbSemeterArr;
    }

    private void fGetData() {
        try {
            regFormBLL = new clsRegisterForm_BLL();
            if (idFaculty == "01") {
                idFaculty = "";
                regFormPublic.setIdFaculty(idFaculty);
            } else {
                itemFaculty = (Item_Cbx) cbFaculty.getSelectedItem();
                idFaculty = itemFaculty.getId();
                regFormPublic.setIdFaculty(idFaculty);
            }

            if (cbMayjors.getSelectedIndex() == 0 || idMayjors == "Tất cả") {
                idMayjors = "";
                regFormPublic.setIdMayjors(idMayjors);
            } else {
                itemMayjors = (Item_Cbx) cbMayjors.getSelectedItem();
                idMayjors = itemMayjors.getId();
                regFormPublic.setIdMayjors(idMayjors);
            }
            if (cbYearApply.getSelectedIndex() == 0 || yearOfApply == "Tất cả") {
                yearOfApply = "";
                regFormPublic.setYearOfApply(yearOfApply);
            } else {
                itemYearApply = (Item_Cbx) cbYearApply.getSelectedItem();
                yearOfApply = itemYearApply.getDescription();
                regFormPublic.setYearOfApply(yearOfApply);
            }
            if (cbSemeter.getSelectedIndex() == 0) {
                noSemeter = null;
                regFormPublic.setNoSemeter(noSemeter);
            } else {
                itemNoSemeter = (Item_Cbx) cbSemeter.getSelectedItem();
                noSemeter = Integer.parseInt(itemNoSemeter.getDescription());
                regFormPublic.setNoSemeter(noSemeter);
            }
            if (cbScholastic.getSelectedIndex() == 0) {
                year1 = null;
                year2 = null;
                regFormPublic.setY1(year1);
                regFormPublic.setY2(year2);
            } else {
                itemYear = (Item_Cbx) cbScholastic.getSelectedItem();
                String scholastic = itemYear.getDescription();
                String[] yearArr = scholastic.split("-");
                year1 = Integer.parseInt(yearArr[0]);
                year2 = Integer.parseInt(yearArr[1]);
                regFormPublic.setY1(year1);
                regFormPublic.setY2(year2);
            }
            rs = regFormBLL.LOAD_LISTST_FEE(regFormPublic);

            fSetTableListStudent();
            fFillDataToTBListStudent1();
        } catch (Exception ex) {
            throw ex;
        }

    }

    private void fFillCombobox_cbState() {
        selectedData = "";
                    getNameStudent = "";
        modelCondition = new DefaultComboBoxModel(fAddtoArrr_fill_cbCondition().toArray());
        cbCoFilter.setModel(modelCondition);
    }

    private void fFillCombobox_cbScholatic() throws Exception {
        modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
        cbScholastic.setModel(modelScholatis);

        fGetData();
        cbScholastic.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                selectedData = "";
                    getNameStudent = "";
                fGetData();
            }
        });
    }

    private void fFillCombobox_cbSemeter() {
        modelSemeter = new DefaultComboBoxModel(fAddtoArr_fill_cbSemeter().toArray());
        cbSemeter.setModel(modelSemeter);
        modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
        cbScholastic.setModel(modelScholatis);
        fGetData();
        cbSemeter.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                selectedData = "";
                    getNameStudent = "";
                fGetData();
            }
        });
    }

    //
    private ArrayList<Item_Cbx> fAddtoArrr_fill_cbCondition() {
        ArrayList<Item_Cbx> cbCondition = new ArrayList<>();
        cbCondition.add(new Item_Cbx("01", "Tất cả"));
        cbCondition.add(new Item_Cbx("02", "Đã hoàn thành học phí"));
        cbCondition.add(new Item_Cbx("03", "Chưa hoàn thành học phí"));
        return cbCondition;
    }

    /**
     * @HungNgoc Fill vào combobox của mục Ngành
     */
    private void fFillCombobox_cbMayjors() {
        try {
            modelMayjors = new DefaultComboBoxModel(fAddtoArrr_fill_cbMayjors().toArray());
            cbMayjors.setModel(modelMayjors);
            modelYearApply = new DefaultComboBoxModel(fAddtoArr_fill_cbYearApply().toArray());
            cbYearApply.setModel(modelYearApply);
            modelSemeter = new DefaultComboBoxModel(fAddtoArr_fill_cbSemeter().toArray());
            cbSemeter.setModel(modelSemeter);
            modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
            cbScholastic.setModel(modelScholatis);
            fGetData();
            cbMayjors.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    selectedData = "";
                    getNameStudent = "";
                    modelCondition = new DefaultComboBoxModel(fAddtoArrr_fill_cbCondition().toArray());
                    cbCoFilter.setModel(modelCondition);
                    fGetData();
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @Hung Load du lieu ten khoa tu store procudure vao cbFaculty, Ham viet
     * lai
     */
    private void fFillCombobox_cbFaculty() {
        try {
            rs = FaBLL.fLoad_NameOfFaculty();
            while (rs.next()) {
                dfModel.addElement(new Item_Cbx(rs.getNString(1), rs.getNString(2)));
                cbFaculty.setModel(dfModel);
            }
            cbFaculty.addItem(new Item_Cbx("01", "Tất cả"));
            itemFaculty = (Item_Cbx) cbFaculty.getSelectedItem();
            idFaculty = itemFaculty.getId();
            modelMayjors = new DefaultComboBoxModel(fAddtoArrr_fill_cbMayjors().toArray());
            cbMayjors.setModel(modelMayjors);
            modelYearApply = new DefaultComboBoxModel(fAddtoArr_fill_cbYearApply().toArray());
            cbYearApply.setModel(modelYearApply);
            modelSemeter = new DefaultComboBoxModel(fAddtoArr_fill_cbSemeter().toArray());
            cbSemeter.setModel(modelSemeter);
            modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
            cbScholastic.setModel(modelScholatis);
            fGetData();
            cbFaculty.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        selectedData = "";
                    getNameStudent = "";
                        itemFaculty = (Item_Cbx) cbFaculty.getSelectedItem();
                        idFaculty = itemFaculty.getId();
                        modelMayjors = new DefaultComboBoxModel(fAddtoArrr_fill_cbMayjors().toArray());
                        cbMayjors.setModel(modelMayjors);
                        modelCondition = new DefaultComboBoxModel(fAddtoArrr_fill_cbCondition().toArray());
                        cbCoFilter.setModel(modelCondition);

                        fGetData();

                    } catch (Exception ex) {
                        Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Load du lieu vao combobox cua Nam Nhap Hoc
     */
    private void FillCombobox_cbYearApply() {
        try {
            modelYearApply = new DefaultComboBoxModel(fAddtoArr_fill_cbYearApply().toArray());
            cbYearApply.setModel(modelYearApply);
            modelSemeter = new DefaultComboBoxModel(fAddtoArr_fill_cbSemeter().toArray());
            cbSemeter.setModel(modelSemeter);
            modelScholatis = new DefaultComboBoxModel(fAddtoArr_fill_cbScholastic().toArray());
            cbScholastic.setModel(modelScholatis);
            fGetData();
            cbYearApply.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    selectedData = "";
                    getNameStudent = "";
                    modelCondition = new DefaultComboBoxModel(fAddtoArrr_fill_cbCondition().toArray());
                    cbCoFilter.setModel(modelCondition);
                    fGetData();
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jXLabel60 = new org.jdesktop.swingx.JXLabel();
        jXLabel61 = new org.jdesktop.swingx.JXLabel();
        jXLabel62 = new org.jdesktop.swingx.JXLabel();
        jXLabel63 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        cbFaculty = new org.jdesktop.swingx.JXComboBox();
        cbMayjors = new org.jdesktop.swingx.JXComboBox();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        cbYearApply = new org.jdesktop.swingx.JXComboBox();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        cbSemeter = new org.jdesktop.swingx.JXComboBox();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        cbScholastic = new org.jdesktop.swingx.JXComboBox();
        cbCoFilter = new org.jdesktop.swingx.JXComboBox();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jPanel28 = new javax.swing.JPanel();
        jXPanel14 = new org.jdesktop.swingx.JXPanel();
        jXLabel71 = new org.jdesktop.swingx.JXLabel();
        sField = new org.jdesktop.swingx.JXSearchField();
        jPanel32 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        scrollPaneListStudent = new javax.swing.JScrollPane();
        tb_ListStudent = new org.jdesktop.swingx.JXTable();
        jPanel3 = new javax.swing.JPanel();
        scrStudentDetail = new javax.swing.JScrollPane();
        tbDetailStudent = new org.jdesktop.swingx.JXTable();
        jPanel22 = new javax.swing.JPanel();
        btReoport = new org.jdesktop.swingx.JXButton();
        btDetail = new org.jdesktop.swingx.JXButton();

        setLayout(new java.awt.BorderLayout());

        jXLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jXLabel1.setText("TÌNH TRẠNG ĐÓNG HỌC PHÍ");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jXLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Điều kiện chọn"));

        jXLabel60.setText("Sinh viên đã hoàn thành học phí");

        jXLabel61.setBackground(new java.awt.Color(255, 0, 51));
        jXLabel61.setForeground(new java.awt.Color(255, 0, 51));
        jXLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statusRed.png"))); // NOI18N

        jXLabel62.setBackground(new java.awt.Color(255, 0, 51));
        jXLabel62.setForeground(new java.awt.Color(255, 0, 51));
        jXLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statusGreen.png"))); // NOI18N

        jXLabel63.setText("Sinh viên chưa hoàn thành học phí");

        jXLabel3.setText("Khoa:");

        jXLabel4.setText("Ngành:");

        jXLabel5.setText("Năm nhập học:");

        jXLabel13.setText("Học kỳ:");

        jXLabel14.setText("Năm học:");

        cbCoFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCoFilterItemStateChanged(evt);
            }
        });

        jXLabel6.setText("Điều kiện lọc:");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCoFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbYearApply, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(cbMayjors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSemeter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbScholastic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMayjors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSemeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbScholastic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCoFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jXLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jXLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel23Layout.createSequentialGroup()
                        .addComponent(jXLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jXLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        jPanel20.add(jPanel23, java.awt.BorderLayout.WEST);

        jXLabel71.setText("Giá trị tìm kiếm:");

        sField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFieldActionPerformed(evt);
            }
        });
        sField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jXPanel14Layout = new javax.swing.GroupLayout(jXPanel14);
        jXPanel14.setLayout(jXPanel14Layout);
        jXPanel14Layout.setHorizontalGroup(
            jXPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel14Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jXLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jXPanel14Layout.setVerticalGroup(
            jXPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jXPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sinh viên"));

        scrollPaneListStudent.setViewportView(tb_ListStudent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneListStudent, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneListStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết thu học phí sinh viên"));

        scrStudentDetail.setViewportView(tbDetailStudent);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrStudentDetail, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrStudentDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(jXPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel28, java.awt.BorderLayout.CENTER);

        add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btReoport.setText("Xuất báo cáo");
        btReoport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReoportActionPerformed(evt);
            }
        });

        btDetail.setText("In chi tiết");
        btDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(834, Short.MAX_VALUE)
                .addComponent(btReoport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btReoport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel22, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void sFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFieldActionPerformed

    private void cbCoFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCoFilterItemStateChanged
        // TODO add your handling code here:
        if (cbCoFilter.getSelectedItem().toString().trim() == "Tất cả") {
            tb_ListStudent.setModel(dtmListStudent);
        } else {
            if (cbCoFilter.getSelectedItem().toString().trim() == "Đã hoàn thành học phí") {
                ReloadDataTable(dtmListStudent, true);
            } else {
                ReloadDataTable(dtmListStudent, false);
            }
        }
    }//GEN-LAST:event_cbCoFilterItemStateChanged

    private void btReoportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReoportActionPerformed
        // TODO add your handling code here:
        try {
            conn = new SQLServerConnector();
            HashMap<String, Object> parameter = new HashMap<String, Object>();
            itemFaculty = (Item_Cbx) cbFaculty.getSelectedItem();
            itemMayjors = (Item_Cbx) cbMayjors.getSelectedItem();
            itemYear = (Item_Cbx) cbScholastic.getSelectedItem();
            itemNoSemeter = (Item_Cbx) cbSemeter.getSelectedItem();
            String facultyName = itemFaculty.getDescription();
            idFaculty = itemFaculty.getId();
            String mayjorsName = itemMayjors.getDescription();
            String scholastic = itemYear.getDescription();
            String semeter = itemNoSemeter.getDescription();
            itemStateRegister = (Item_Cbx) cbCoFilter.getSelectedItem();
            String _stateRegister = itemStateRegister.getDescription();
            //{call LOAD_LIST_STUDENT_ALLPARAMETER($P{rpIdFaculty},$P{rpIdMayjors},$P{rpYearOfApply},$P{rpNoSemeter},$P{rpYear1},$P{rpYear2})}

            if (idFaculty == "01") {
                String _idFaculty = "";
                parameter.put("rp_IdFaculty", String.valueOf(_idFaculty));
            } else {
                itemFaculty = (Item_Cbx) cbFaculty.getSelectedItem();
                String _idFaculty = itemFaculty.getId();
                parameter.put("rp_IdFaculty", String.valueOf(_idFaculty));
            }

            if (cbMayjors.getSelectedIndex() == 0 || idMayjors == "Tất cả") {
                String _idMayjors = "";
                parameter.put("rp_IdMayjors", String.valueOf(_idMayjors));
            } else {
                itemMayjors = (Item_Cbx) cbMayjors.getSelectedItem();
                String _idMayjors = itemMayjors.getId();
                parameter.put("rp_IdMayjors", String.valueOf(_idMayjors));
            }
            if (cbYearApply.getSelectedIndex() == 0 || yearOfApply == "Tất cả") {
                String _yearOfApply = "";
                parameter.put("rp_YearOfApply", String.valueOf(_yearOfApply));
            } else {
                itemYearApply = (Item_Cbx) cbYearApply.getSelectedItem();
                String _yearOfApply = itemYearApply.getDescription();
                parameter.put("rp_YearOfApply", String.valueOf(_yearOfApply));
            }
            if (cbSemeter.getSelectedIndex() == 0) {
                Integer _noSemeter = null;
                parameter.put("rp_Semeter", _noSemeter);
            } else {
                itemNoSemeter = (Item_Cbx) cbSemeter.getSelectedItem();
                Integer _noSemeter = Integer.parseInt(itemNoSemeter.getDescription());
                parameter.put("rp_Semeter", Integer.valueOf(_noSemeter));
            }
            if (cbScholastic.getSelectedIndex() == 0) {
                Integer _year1 = null;
                Integer _year2 = null;
                parameter.put("rp_Year1", _year1);
                parameter.put("rp_Year2", _year2);
            } else {
                itemYear = (Item_Cbx) cbScholastic.getSelectedItem();
                String mscholastic = itemYear.getDescription();
                String[] yearArr = mscholastic.split("-");
                Integer _year1 = Integer.parseInt(yearArr[0]);
                Integer _year2 = Integer.parseInt(yearArr[1]);
                parameter.put("rp_Year1", _year1);
                parameter.put("rp_Year2", _year2);
            }
            parameter.put("rp_NameFaculty", String.valueOf(facultyName));
            parameter.put("rp_NameMayjors", String.valueOf(mayjorsName));
            parameter.put("rp_State", String.valueOf(_stateRegister));
            parameter.put("rpSemeterText", String.valueOf(semeter));
            // InputStream input = new FileInputStream(new File("C:\\Users\\Hung\\SkyDrive\\Tai lieu hoc tap\\Dev Project\\Java\\QLGiaoVu_DeMon\\src\\GUI\\Report\\rp_RegisterSubject.jrxml"));
            InputStream input = this.getClass().getClassLoader().getResourceAsStream("GUI/Report/rp_StateFee.jrxml");
            JasperDesign design = JRXmlLoader.load(input);
            JasperReport report = JasperCompileManager.compileReport(design);
            JasperPrint jpr = JasperFillManager.fillReport(report, parameter, conn.getConnect());
            JasperViewer.viewReport(jpr, false);

        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btReoportActionPerformed

    private void btDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetailActionPerformed
        // TODO add your handling code here:
         try {
            if (selectedData == "") {
                JOptionPane.showMessageDialog(tbDetailStudent, "Bạn chưa chọn sinh viên để xuất phiếu.\nVui lòng chọn sinh viên trên bảng Danh sách sinh viên.");
            } else {
                if (JOptionPane.showConfirmDialog(tbDetailStudent, "Bạn có muốn xuất phiếu danh sách đăng ký môn học cho sinh viên?\nMSSV: " + selectedData + "\nHọ tên: " + getNameStudent) == JOptionPane.YES_OPTION) {
                    conn = new SQLServerConnector();
                    HashMap<String, Object> parameter = new HashMap<String, Object>();
                    parameter.put("rpIdStudent", selectedData);
                    parameter.put("nameStudent_RP", getNameStudent);
                     parameter.put("facultyName_RP", getFaculty);
                     parameter.put("mayjorsName_RP", getMayjors);
                     parameter.put("scholastic_RP", getScholatic);
                     parameter.put("semeter_RP", getSemeter);
                     Integer semeter = Integer.parseInt(getSemeter);
                     parameter.put("rpSemeter", semeter);
                      String[] yearArr = getScholatic.split("-");
                Integer _year1 = Integer.parseInt(yearArr[0]);
                Integer _year2 = Integer.parseInt(yearArr[1]);
                parameter.put("rpYear2", _year1);
                parameter.put("rpYear2", _year2);
                    InputStream input = this.getClass().getClassLoader().getResourceAsStream("GUI/Report/rp_StateFeeDetail.jrxml");
                    JasperDesign design = JRXmlLoader.load(input);
                    JasperReport report = JasperCompileManager.compileReport(design);
                    JasperPrint jpr = JasperFillManager.fillReport(report, parameter, conn.getConnect());
                    JasperViewer.viewReport(jpr, false);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDetailActionPerformed

    private void sFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sFieldKeyTyped
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String search = sField.getText();
            stPublic.setName(search);
            itemNoSemeter = (Item_Cbx) cbSemeter.getSelectedItem();
            String _noSemeter = itemNoSemeter.getDescription();
            if (_noSemeter == "Tất cả") {
                noSemeter = null;
                regFormPublic.setNoSemeter(noSemeter);
            } else {
                noSemeter = Integer.parseInt(_noSemeter);
                regFormPublic.setNoSemeter(noSemeter);
            }
            if (cbScholastic.getSelectedIndex() == 0) {
                Integer _year1 = null;
                Integer _year2 = null;
                regFormPublic.setY1(_year1);
                regFormPublic.setY2(_year2);
            } else {
                itemYear = (Item_Cbx) cbScholastic.getSelectedItem();
                String mscholastic = itemYear.getDescription();
                String[] yearArr = mscholastic.split("-");
                Integer _year1 = Integer.parseInt(yearArr[0]);
                Integer _year2 = Integer.parseInt(yearArr[1]);
                regFormPublic.setY1(_year1);
                regFormPublic.setY2(_year2);
            }
            rs = regFormBLL.SEARCH_STUDENT_FEE(regFormPublic, stPublic);
            do{
                
                fSetTableListStudent();
                fFillDataToTBListStudent1();
            }while(rs.next());
        } catch (SQLException ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sFieldKeyTyped

     public void ReloadDataTable(DefaultTableModel old, boolean cd) {
        String[] titleTableListStudent = {"MSSV", "Họ và Tên", "Khóa", "Khoa", "Ngành Học","Học Kỳ","Năm Học","Tổng Tiền Đăng Ký", "Số Tiền Phải Đóng","Số Tiền Nợ"};
        DefaultTableModel cd1 = new DefaultTableModel(titleTableListStudent, 0);
        DefaultTableModel cd2 = new DefaultTableModel(titleTableListStudent, 0);

        for (int i = 0; i < old.getRowCount(); i++) {
            Vector rows = new Vector();
            rows = (Vector) old.getDataVector().elementAt(i);
            if (Double.parseDouble(rows.get(9).toString()) <= 0) {
                cd1.addRow(rows);
            } else {
                cd2.addRow(rows);
            }
        }
        if (cd) {
            tb_ListStudent.setModel(cd1);
        } else {
            tb_ListStudent.setModel(cd2);
        }
    }
    
    
    private void fSetTableListStudent() {

        String[] titleTableListStudent = {"MSSV", "Họ và Tên", "Khóa", "Khoa", "Ngành Học","Học Kỳ","Năm Học","Tổng Tiền Đăng Ký", "Số Tiền Phải Đóng","Số Tiền Nợ"};
        LineNumberTableRowHeader lineRow = new LineNumberTableRowHeader(scrollPaneListStudent, tb_ListStudent);
        lineRow.setBackground(new Color(240, 240, 240));
        scrollPaneListStudent.setRowHeaderView(lineRow);
        dtmListStudent = new DefaultTableModel(titleTableListStudent, 0);
        tb_ListStudent.setModel(dtmListStudent);
        tb_ListStudent.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    
    
    private void fSetTableListStudentDetail() {

        String[] titleTableListStudent = {"Mã Phiếu Thu", "Tên Nhân Viên", "Ngày Thu", "Số Tiền Thu","Số Tiền Còn Nợ"};
        LineNumberTableRowHeader lineRow = new LineNumberTableRowHeader(scrollPaneListStudent, tbDetailStudent);
        lineRow.setBackground(new Color(240, 240, 240));
        scrStudentDetail.setRowHeaderView(lineRow);
        dtmListStudentDetail = new DefaultTableModel(titleTableListStudent, 0);
        tbDetailStudent.setModel(dtmListStudentDetail);
        tbDetailStudent.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    
    private void eventOnTable() {
        ListSelectionModel cellSelectionModel = tb_ListStudent.getSelectionModel();
        // cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                try {
                    int selectedRow1 = tb_ListStudent.getSelectedRow();
                    if (selectedRow1 < 0) {
                        return;
                    }
                    selectedData = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 0));
                    getNameStudent = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 1));
                    getTotal = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 5));
                    getFaculty = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 3));
                     getMayjors = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 4));
                      getSemeter = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 5));
                       getScholatic = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 6));
                    //JOptionPane.showMessageDialog(tb_ListStudent, selectedData);
                    stPublic.setIdStudent(selectedData);
                    String _semeter = String.valueOf(tb_ListStudent.getValueAt(selectedRow1, 5));
                    Integer semeter = null;
                    if(_semeter=="Tất cả")
                    {
                        regFormPublic.setNoSemeter(semeter);
                    }else{
                        semeter = Integer.parseInt(_semeter);
                        regFormPublic.setNoSemeter(semeter);
                    }
                    itemYear = (Item_Cbx) cbScholastic.getSelectedItem();
                    String yearscholastic = itemYear.getDescription();
                    Integer _year1 = null;
                    Integer _year2 = null;
                    if (yearscholastic == "Tất cả") {
                        regFormPublic.setY1(_year1);
                        regFormPublic.setY2(_year2);
                    } else {
                        String[] yearArr = yearscholastic.split("-");
                        _year1 = Integer.parseInt(yearArr[0]);
                        _year2 = Integer.parseInt(yearArr[1]);
                        regFormPublic.setY1(_year1);
                        regFormPublic.setY2(_year2);
                    }
                    rs = regFormBLL.LOAD_LISTST_FEE_DETAIL(regFormPublic,stPublic);
                    do{
                    fSetTableListStudentDetail();
                        fFillDataToTBListStudentDetail();
                    }while(rs.next());
                } catch (Exception ex) {
                    Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }

    private void fFillDataToTBListStudentDetail(){
        try {
            while (rs.next()) {
                Vector data_Rows = new Vector();
                data_Rows.add(rs.getObject(1));
                data_Rows.add(rs.getObject(2));
                data_Rows.add(rs.getObject(3));
                data_Rows.add(rs.getObject(4));
                data_Rows.add(rs.getObject(5));
                dtmListStudentDetail.addRow(data_Rows);
            }
        } catch (SQLException ex) {
            Logger.getLogger(rpStateFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fFillDataToTBListStudent1() {
        try {

            while (rs.next()) {
                Vector data_Rows = new Vector();
                data_Rows.add(rs.getObject(1));
                data_Rows.add(rs.getObject(2));
                data_Rows.add(rs.getObject(3));
                data_Rows.add(rs.getObject(4));
                data_Rows.add(rs.getObject(5));
                data_Rows.add(rs.getObject(7));
                Object y1 =  rs.getObject(8);
                Object y2 = rs.getObject(9);
                String y = y1+"-"+y2;
                data_Rows.add(y);
                 data_Rows.add(rs.getObject(10));
                  data_Rows.add(rs.getObject(11));
                  data_Rows.add(rs.getObject(12));
                dtmListStudent.addRow(data_Rows);
            }

        } catch (Exception ex) {
            Logger.getLogger(rpRegisterSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btDetail;
    private org.jdesktop.swingx.JXButton btReoport;
    private org.jdesktop.swingx.JXComboBox cbCoFilter;
    private org.jdesktop.swingx.JXComboBox cbFaculty;
    private org.jdesktop.swingx.JXComboBox cbMayjors;
    private org.jdesktop.swingx.JXComboBox cbScholastic;
    private org.jdesktop.swingx.JXComboBox cbSemeter;
    private org.jdesktop.swingx.JXComboBox cbYearApply;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel60;
    private org.jdesktop.swingx.JXLabel jXLabel61;
    private org.jdesktop.swingx.JXLabel jXLabel62;
    private org.jdesktop.swingx.JXLabel jXLabel63;
    private org.jdesktop.swingx.JXLabel jXLabel71;
    private org.jdesktop.swingx.JXPanel jXPanel14;
    private org.jdesktop.swingx.JXSearchField sField;
    private javax.swing.JScrollPane scrStudentDetail;
    private javax.swing.JScrollPane scrollPaneListStudent;
    private org.jdesktop.swingx.JXTable tbDetailStudent;
    private org.jdesktop.swingx.JXTable tb_ListStudent;
    // End of variables declaration//GEN-END:variables
}
